/* Autogenerated */
import '../tenants/bk-uk/styles/main.scss';
export const TENANT_NAME = 'bk-uk';
export const TENANT_PATH = '/Users/anupvasudeva/projects/webinar/boost-productivity-with-babel/tenants/bk-uk';
import headerTemplate from '../tenants/bk-uk/templates/header/header.html';
import homeTemplate from '../tenants/bk-uk/templates/home/home.html';
import loginTemplate from '../tenants/bk-uk/templates/login/login.html';
import userTemplate from '../tenants/bk-uk/templates/user/user.html';
import usersTemplate from '../tenants/bk-uk/templates/user/users.html';
export {
	headerTemplate,
	homeTemplate,
	loginTemplate,
	userTemplate,
	usersTemplate
};